version: '3.8'

# My Sister's Closet - Receipt Management System
# Portainer Stack Configuration
# 
# BEFORE DEPLOYING:
# 1. Update environment variables in the Portainer stack editor
# 2. Generate a secure JWT_SECRET: openssl rand -base64 32
# 3. Configure SMTP settings if email features are needed
# 4. Update CLIENT_URL with your domain/IP

services:
  server:
    image: ghcr.io/yourusername/msc-server:latest  # Update with your registry
    # OR build from source:
    # build:
    #   context: https://github.com/yourusername/MSC-Label-Maker.git#main:server
    container_name: msc-server
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      # REQUIRED: Generate with: openssl rand -base64 32
      - JWT_SECRET=${JWT_SECRET}
      # OPTIONAL: Email configuration (leave empty to disable)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-}
      # Update with your domain or IP
      - CLIENT_URL=${CLIENT_URL:-http://localhost}
    volumes:
      - msc-database:/app/database.sqlite
      - msc-excel-logs:/app/excel-logs
      - msc-temp:/app/temp
    networks:
      - msc-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5002/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)}).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  client:
    image: ghcr.io/yourusername/msc-client:latest  # Update with your registry
    # OR build from source:
    # build:
    #   context: https://github.com/yourusername/MSC-Label-Maker.git#main:client
    container_name: msc-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - msc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  msc-network:
    driver: bridge
    name: msc-network

volumes:
  msc-database:
    driver: local
  msc-excel-logs:
    driver: local
  msc-temp:
    driver: local